name: test-merge-group

on:
  merge_group:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
      - id: comment
        name: comment
        run: gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "test comment on merge group event"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # fail the workflow
      - id: fail
        name: fail
        run: exit 1

    