name: test-merge-group

on:
  merge_group:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
      - id: comment
        name: comment
        run: echo "test comment on merge group event"
      # fail the workflow
      - id: fail
        name: fail
        run: exit 1

    