name: test-pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
        - id: checkout
          name: checkout
          uses: actions/checkout@v3
        - id: comment
          name: comment
          run: echo "test comment on pull request event"

    